import { build, transform } from 'esbuild';
import { marked } from 'marked';
import { readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import { watch } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))),dist=path.join(root,'dist');
const read=file=>readFile(path.join(root,file),'utf8');
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=text=>text.replace(/&#39;|&#x27;/gi,"'").toLowerCase().replace(/[^a-z0-9\s-]/g,'').trim().replace(/\s+/g,'-');
marked.use({renderer:{heading({tokens,depth}){const text=this.parser.parseInline(tokens);return `<h${depth} id="${slug(text.replace(/<[^>]*>/g,''))}">${text}</h${depth}>\n`;}}});

export async function generate(){
 const config=JSON.parse(await read('site.config.json'));
 for(const key of ['analysisUrl','repositoryUrl'])if(config[key]&&!/^https:\/\//.test(config[key]))throw Error(`${key} must be empty or an HTTPS URL`);
 await mkdir(dist,{recursive:true});await cp(path.join(root,'public'),dist,{recursive:true});
 await build({entryPoints:['src/explore.js','src/site.js'].map(p=>path.join(root,p)),outdir:path.join(dist,'assets'),bundle:true,minify:true,splitting:true,format:'esm',target:['es2022'],legalComments:'linked'});
 await writeFile(path.join(dist,'assets/style.css'),(await transform(await read('src/style.css'),{loader:'css',minify:true})).code);
 const siteUrl=new URL(config.siteUrl);
 if(siteUrl.protocol!=='https:'||!siteUrl.pathname.endsWith('/')||siteUrl.search||siteUrl.hash)throw Error('siteUrl must be an HTTPS base URL ending in /');
 const footer=`<footer class="footer"><p><strong>Darker Discovered</strong> · An investigation into Psygnosis’s Darker.<br>Original game and artwork belong to their respective creators. City and model views reconstructed from game data.</p><div>${config.analysisUrl?`<a href="${escape(config.analysisUrl)}">Full technical analysis ↗</a>`:'The full technical analysis will be published separately.'}${config.repositoryUrl?`<br><a href="${escape(config.repositoryUrl)}">Site source ↗</a>`:''}</div></footer>`;
 const page=(key,title,body,{viewer=false,toc=''}={})=>{
  const base=key==='home'?'./':'../';
  const url=new URL(key==='home'?'':`${key}/`,siteUrl).href;
  const image=new URL('images/social-preview.jpg',siteUrl).href;
  const socialTitle=`${title} · ${config.title}`;
  const imageAlt='Darker Discovered: the reconstructed Delphi city, with the title Taking Darker apart.';
  const metadata=[
   ['og:title',socialTitle],['og:description',config.description],
   ['og:type',key==='story'?'article':'website'],['og:site_name',config.title],['og:url',url],
   ['og:image',image],['og:image:type','image/jpeg'],['og:image:width','1200'],['og:image:height','630'],['og:image:alt',imageAlt]
  ].map(([property,content])=>`<meta property="${property}" content="${escape(content)}">`).join('');
  const twitter=[['card','summary_large_image'],['title',socialTitle],['description',config.description],['image',image],['image:alt',imageAlt]]
   .map(([name,content])=>`<meta name="twitter:${name}" content="${escape(content)}">`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${escape(config.description)}"><meta name="color-scheme" content="light dark"><meta name="theme-color" media="(prefers-color-scheme: light)" content="${viewer?'#0e1925':'#f5f3ec'}"><meta name="theme-color" media="(prefers-color-scheme: dark)" content="${viewer?'#0e1925':'#101923'}">${metadata}${twitter}<link rel="canonical" href="${escape(url)}"><title>${escape(title)} · Darker Discovered</title><link rel="icon" href="${base}images/icon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}assets/style.css"></head><body data-page="${key}" class="${viewer?'dark-page':''}"><a href="#main" class="skip">Skip to content</a><header class="topbar"><a class="brand" href="${base}">DARKER<span>Discovered</span></a><button class="menu-toggle" data-menu aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" class="nav-links" aria-label="Main navigation">${[['story','The investigation'],['cities','Explore cities'],['models','Model gallery']].map(([id,label])=>`<a href="${base}${id}/" ${id===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main">${body}</main>${footer}<script type="module" src="${base}assets/site.js"></script>${viewer?`<script type="module" src="${base}assets/explore.js"></script>`:''}</body></html>`;
 };
 const home=`<section class="hero"><div class="hero-copy"><div class="eyebrow">Software archaeology / Psygnosis / 1995</div><h1>Taking Darker<br>apart.</h1><p>The cities, ships and undocumented cheats of Psygnosis’s 1995 flight game, recovered from the original DOS files.</p><div class="actions"><a class="button" href="cities/">Explore the cities <span aria-hidden="true">↗</span></a><a class="button secondary" href="story/">Read the investigation</a></div></div><div class="hero-note">DELPHI<br>Reconstructed from the original game data.</div></section><section class="intro"><div><p class="eyebrow">The first problem</p><h2>It started with the executable.</h2></div><div><p>The first obstacle was an executable that ran in DOSBox but looked like nonsense in a disassembler. Once we understood the loader, we could follow the code into the model formats, mission scripts and flight systems.</p><p>It also led us to a working cheat prompt that, as far as we can tell, had gone undocumented since release. Unlimited boost had been there all along.</p></div></section><section class="section"><div class="section-title"><h2>Explore Darker</h2><span class="eyebrow">Retail + two demo releases</span></div><div class="cards"><a class="card" href="cities/"><span class="eyebrow">City explorer</span><img src="images/city-detail.webp" alt="Reconstructed Delphi skyline" width="960" height="600" loading="lazy"><h3>The city maps</h3><p>Explore Delphi, Halon and the tunnels, or compare them with the maps from two earlier demos.</p></a><a class="card" href="models/"><span class="eyebrow">Model gallery</span><img src="images/model-craft.webp" alt="Recovered Caero fighter" width="1200" height="800" loading="lazy"><h3>Buildings and craft</h3><p>Turn the models around, look inside an open hangar, or watch the fountain animation.</p></a><a class="card" href="story/"><span class="eyebrow">Reverse engineering</span><img src="images/star-three.webp" alt="The original game's hidden STAR THREE prompt" width="960" height="720" loading="lazy"><h3>How we worked it out</h3><p>The loader that confused our disassembler, the model format that turned out to be a programming language, and the cheats we found along the way.</p></a></div></section><aside class="note-band"><p><strong>About the viewers.</strong> The models, colours and map layouts come from Darker’s data files. This site draws them with a modern renderer so you can explore them in a browser. Reproducing the original game’s rendering and behaviour is a separate project.</p></aside>`;
 const stage=`<div class="viewport-wrap"><div id="viewport" class="viewport" aria-busy="false"></div><div class="viewport-title"><p class="eyebrow" id="era-label"></p><h2 id="collection-name"></h2></div><div class="viewport-buttons"><button id="zoom-in" aria-label="Zoom in">+</button><button id="zoom-out" aria-label="Zoom out">−</button><button id="reset">Reset view</button></div></div><p id="viewer-status" class="viewer-status" role="status">Loading…</p><p class="fallback" id="fallback" hidden>The interactive view needs WebGL. You can still explore the screenshots and diagrams in <a href="../story/">the investigation</a>.</p><noscript><p class="fallback">Enable JavaScript to use the viewer, or <a href="../story/">read the illustrated investigation</a>.</p></noscript>`;
 const cities=`<header class="page-intro"><p class="eyebrow">City explorer</p><h1>Darker’s cities</h1><p>Choose a map from the retail game or either demo. Click a building to highlight others of the same type, then open it in the model gallery for a closer look.</p></header><section class="exhibit" aria-label="City explorer"><div class="toolbar"><label>Release<select id="era"></select></label><label>World<select id="map"></select></label><label>Find a structure<select id="type"></select></label><label class="check"><input id="isolate" type="checkbox">Only this type</label><label class="check"><input id="flat" type="checkbox">Flat colours</label><button id="focus" disabled>Visit selection</button><button id="street">Street level</button></div>${stage}<div class="selection"><p id="selection"></p><a id="model-link" hidden>Open in model gallery ↗</a></div></section><p class="exhibit-caption">Mouse: drag to orbit, right-drag to move across the ground, scroll to zoom. Touch: one finger to orbit, two to move or zoom. The maps, models and colours come from the game. This viewer keeps the beacons lit and uses modern projection, without the original visibility checks or distance fading.</p>`;
 const picks=[['30','special-25','model-craft','The Caero fighter'],['30','city-1','model-beacon','An energy beacon'],['30','city-120','model-fountain','A fountain ornament'],['199308','city-13','model-dish','The demo’s satellite dish']];
 const models=`<header class="page-intro"><p class="eyebrow">Model gallery</p><h1>Buildings, craft and effects</h1><p>Choose a collection and an object to view. Some models have alternate forms, moving gates or animation; their controls appear when you select them.</p></header><section class="exhibit" aria-label="Model gallery"><div class="toolbar"><label>Collection<select id="bank"></select></label><label>Show<select id="category"><option value="city">Buildings &amp; scenery</option><option value="special">Craft &amp; effects</option></select></label><label>Search by name or number<input type="search" id="search" placeholder="e.g. beacon or 17"></label><label>Object<select id="model"></select></label></div><div class="toolbar model-tools"><label id="states-control" hidden>Appearance<select id="state"></select></label><label id="gate-control" hidden>Gate extension<input id="gate" type="range" min="0" max="59392" step="256" value="0"></label><label class="check" id="animation-control" hidden><input id="animate" type="checkbox">Animate</label><label class="check"><input id="flat" type="checkbox">Flat colours</label><div id="tags" class="tags"></div></div>${stage}<div class="selection"><p id="model-title"></p><span>Drag to rotate · scroll to zoom</span></div></section><p class="exhibit-caption">Some entries share a model or form part of a larger object. “Not placed on maps” means no direct placement was found; a script or another object may still use that model. Colours come from the game’s palettes, with simplified handling of visibility tests and colours that change during play.</p><section class="section"><div class="section-title"><h2>Try these models</h2></div><div class="highlights">${picks.map(([bank,model,image,title])=>`<a class="highlight" href="?bank=${bank}&amp;model=${model}"><img src="../images/${image}.webp" alt="${title}" width="600" height="460" loading="lazy"><span>${title} ↗</span></a>`).join('')}</div></section>`;
 const markdown=await read('content/investigation.md');const headings=marked.lexer(markdown).filter(t=>t.type==='heading'&&t.depth===2);
 const story=`<header class="page-intro"><p class="eyebrow">Reverse engineering</p><h1>Inside the DOS files</h1><p>An account of taking Darker apart: what worked, what we got wrong, and what turned up in the code.</p></header><div class="story-layout"><nav class="contents" aria-label="Article contents"><p class="eyebrow">In this investigation</p><ol>${headings.map(h=>`<li><a href="#${slug(h.text)}">${escape(h.text)}</a></li>`).join('')}</ol></nav><article class="article">${marked.parse(markdown)}</article></div>`;
 for(const [key,title,body,viewer] of [['home','Inside Darker',home,false],['cities','City explorer',cities,true],['models','Model gallery',models,true],['story','The investigation',story,false]]){
  const dir=key==='home'?dist:path.join(dist,key);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'index.html'),page(key,title,body,{viewer}));
 }
 await writeFile(path.join(dist,'.nojekyll'),'');
 await writeFile(path.join(dist,'404.html'),page('home','Page not found','<section class="page-intro"><h1>Page not found</h1><p>This page could not be found. Use your browser’s Back button to return to the investigation.</p></section>'));
 console.log('Built Darker Discovered → dist/');
}
await rm(dist,{recursive:true,force:true});await generate();
if(process.argv.includes('--serve')){
 const {serve}=await import('./serve.mjs');await serve();let timer,building=false,pending=false;
 const rebuild=async()=>{if(building){pending=true;return}building=true;try{await generate()}catch(e){console.error(e)}finally{building=false;if(pending){pending=false;rebuild()}}};
 for(const folder of ['src','content','public'])watch(path.join(root,folder),{recursive:true},()=>{clearTimeout(timer);timer=setTimeout(rebuild,150)});
 watch(path.join(root,'site.config.json'),()=>rebuild());
}
